apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-manager-server.fullname" . }}
  labels:
    {{- include "job-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    httpPort: {{ .Values.httpPort }}
    grpcPort: {{ .Values.grpcPort }}
    workerServiceGrpcPort: {{ .Values.workerServiceGrpcPort }}
    fileManagerServerAddr: {{ .Values.fileManagerServerAddr }}
    modelManagerServerAddr: {{ .Values.modelManagerServerAddr }}
    sessionManagerServerEndpoint: {{ .Values.sessionManagerServerEndpoint }}
    database:
      host: {{ .Values.global.database.host }}
      port: {{ .Values.global.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.global.database.username }}
      passwordEnvName: DB_PASSWORD
      ssl:
        model: {{ .Values.global.database.ssl.mode }}
        rootCert: {{ .Values.global.database.ssl.rootCert }}
    auth:
      enable: {{ .Values.global.auth.enable }}
      rbacInternalServerAddr: {{ .Values.global.auth.rbacInternalServerAddr }}
    notebook:
      imageTypes:
        {{- toYaml .Values.notebook.imageTypes | nindent 8 }}
    batchJob:
      images:
        {{- toYaml .Values.batchJob.images | nindent 8 }}
