apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-manager-server.fullname" . }}
  labels:
    {{- include "job-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    grpcPort: {{ .Values.grpcPort }}
    httpPort: {{ .Values.httpPort }}
    fileManagerServerAddr: {{ .Values.fileManagerServerAddr }}
    modelManagerInternalServerAddr: {{ .Values.modelManagerInternalServerAddr }}
    database:
      host: {{ .Values.global.database.host }}
      port: {{ .Values.global.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.global.database.username }}
      passwordEnvName: {{ .Values.global.database.passwordEnvName }}
    jobNamespace: {{ .Values.jobNamespace }}
    debug:
      kubeconfigPath: {{ .Values.debug.kubeconfigPath }}
    auth:
      enable: {{ .Values.global.auth.enable }}
      oidcIssuerUrl: {{ .Values.global.auth.oidcIssuerUrl }}
      oidcClientID: {{ .Values.global.auth.oidcClientID }}
