apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-manager-server.fullname" . }}
  labels:
    {{- include "job-manager-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    grpcPort: {{ .Values.grpcPort }}
    httpPort: {{ .Values.httpPort }}
