apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "job-manager-server.fullname" . }}-grpc
  namespace: {{ .Values.jobNamespace | default .Release.Namespace | quote }}
  labels:
    {{- include "job-manager-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - patch
  - update
