jobPollingInterval: 10s
jobNamespace: default

inferenceManagerAddr:

modelStore:
  enable: false
  mountPath: /models
  pvClaimName:

database:
  host:
  port: 5432
  database: job_manager
  username:
  passwordEnvName: DB_PASSWORD

databaseSecret:
  name:
  key:

debug:
  autoMigrate: false
  kubeconfigPath:

replicaCount: 1
image:
  repository: llm-operator/job-manager-dispatcher
  # TODO(kenji): Change this to IfNotPresent. Currently we set the pullPolicy
  # to Never as it is required to use a loaded image in a Kind cluster.
  pullPolicy: Never

version: latest
