jobPollingInterval: 10s
jobNamespace: default

modelManagerInternalServerAddr:
fileManagerInternalServer:

modelStore:
  enable: false
  mountPath: /models
  pvClaimName:

objectStore:
  s3:
    endpointUrl:
    bucket:

awsSecret:
  name:
  accessKeyIdKey:
  secretAccessKeyKey:

database:
  host:
  port: 5432
  database: job_manager
  username:
  passwordEnvName: DB_PASSWORD

databaseSecret:
  name:
  key:

kubernetesManager:
  enableLeaderElection: false
  metricsBindAddress: :8080
  healthBindAddress: :8081
  pprofBindAddress:

debug:
  autoMigrate: false
  kubeconfigPath:
  useFakeJob: false
  huggingFaceAccessToken:

replicaCount: 1

serviceAccount:
  create: true
  serviceAccountName: job-manager-dispatcher

image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/job-manager
  pullPolicy: IfNotPresent

version:

