global:
  database:
    host:
    port:
    username:

  databaseSecret:
    name:
    key:

  objectStore:
    s3:
      endpointUrl:
      region:
      bucket:

  awsSecret:
    name:
    accessKeyIdKey:
    secretAccessKeyKey:

  llmOperatorBaseURL:

pollingInterval: 10s
job:
  image: public.ecr.aws/v8n3t7y5/llm-operator/fine-tuning
  version: latest
  imagePullPolicy: IfNotPresent
  numGpus: 1

# The following default values work if model-manager-server runs in the same namespace.
fileManagerInternalServerAddr: file-manager-server-internal-grpc:8082
modelManagerInternalServerAddr: model-manager-server-internal-grpc:8082

database:
  database: job_manager

kubernetesManager:
  enableLeaderElection: false
  metricsBindAddress: :8080
  healthBindAddress: :8081
  pprofBindAddress:

kueueIntegration:
  enable: false
  defaultQueueName: default

debug:
  kubeconfigPath:

replicaCount: 1

serviceAccount:
  create: true

image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/job-manager-dispatcher
  pullPolicy: IfNotPresent

version:
