global:
  objectStore:
    s3:
      endpointUrl:
      region:
      bucket:

  awsSecret:
    name:
    accessKeyIdKey:
    secretAccessKeyKey:

  worker:
    registrationKeySecret:
      name:
      key:
    tls:
      enable: false
    # If specified, use this as the address for accessing the control-plane services.
    controlPlaneAddr: ""

pollingInterval: 10s

job:
  image: public.ecr.aws/cloudnatix/llm-operator/fine-tuning
  version: 0.130.0
  imagePullPolicy: IfNotPresent
  numGpus: 1
  wandbApiKeySecret:
    name:
    key:

notebook:
  llmOperatorBaseUrl:
  enablePvc: false
  storageClassName: "standard"
  storageSize: "100Gi"
  mountPath:

# The following default values work if model-manager-server runs in the same namespace.
clusterManagerServerWorkerServiceAddr: cluster-manager-server-worker-service-grpc:8082
jobManagerServerWorkerServiceAddr: job-manager-server-worker-service-grpc:8082
fileManagerServerWorkerServiceAddr: file-manager-server-worker-service-grpc:8082
modelManagerServerWorkerServiceAddr: model-manager-server-worker-service-grpc:8082

database:
  database: job_manager

kubernetesManager:
  enableLeaderElection: false
  metricsBindAddress: :8080
  healthBindAddress: :8081
  pprofBindAddress:

kueueIntegration:
  enable: false
  defaultQueueName: default

debug:
  kubeconfigPath:

replicaCount: 1

serviceAccount:
  create: true

image:
  repository: public.ecr.aws/cloudnatix/llm-operator/job-manager-dispatcher
  pullPolicy: IfNotPresent

podAnnotations:
nodeSelector:
affinity:
tolerations:

version:

ports:
- name: metrics
  containerPort: 8080
  protocol: TCP
- name: health
  containerPort: 8081
  protocol: TCP

resources:
  requests:
    cpu: "250m"
    memory: "500Mi"
  limits:
    cpu: "250m"

livenessProbe:
  httpGet:
    path: /healthz
    port: health
    scheme: HTTP
  initialDelaySeconds: 3
  failureThreshold: 5
  timeoutSeconds: 3

podSecurityContext:
  fsGroup: 2000
securityContext:
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
