jobPollingInterval: 10s

debug:
  autoMigrate: false

replicaCount: 1
image:
  repository: job-manager-dispatcher
  # TODO(kenji): Change this to IfNotPresent. Currently we set the pullPolicy
  # to Never as it is required to use a loaded image in a Kind cluster.
  pullPolicy: Never

version: latest
