global:
  objectStore:
    s3:
      endpointUrl:
      region:
      bucket:

  awsSecret:
    name:
    accessKeyIdKey:
    secretAccessKeyKey:

  llmOperatorBaseUrl:

  ingress:
    ingressClassName:

  worker:
    registrationKeySecret:
      name:
      key:
    tls:
      enable: false

pollingInterval: 10s

job:
  image: public.ecr.aws/cloudnatix/llm-operator/fine-tuning
  version: 0.130.0
  imagePullPolicy: IfNotPresent
  numGpus: 1
  wandbApiKeySecret:
    name:
    key:

notebook:
  ingressClassName:
  gatewayName:
  gatewayNamespace:

# The following default values work if model-manager-server runs in the same namespace.
clusterManagerServerWorkerServiceAddr: cluster-manager-server-worker-service-grpc:8082
jobManagerServerWorkerServiceAddr: job-manager-server-worker-service-grpc:8082
fileManagerServerWorkerServiceAddr: file-manager-server-worker-service-grpc:8082
modelManagerServerWorkerServiceAddr: model-manager-server-worker-service-grpc:8082

database:
  database: job_manager

kubernetesManager:
  enableLeaderElection: false
  metricsBindAddress: :8080
  healthBindAddress: :8081
  pprofBindAddress:

kueueIntegration:
  enable: false
  defaultQueueName: default

debug:
  kubeconfigPath:

replicaCount: 1

serviceAccount:
  create: true

image:
  repository: public.ecr.aws/cloudnatix/llm-operator/job-manager-dispatcher
  pullPolicy: IfNotPresent

podAnnotations:
nodeSelector:
affinity:
tolerations:

version:
