jobPollingInterval: 10s
jobNamespace: default
job:
  image: public.ecr.aws/v8n3t7y5/llm-operator/fine-tuning
  version:
  imagePullPolicy: IfNotPresent

modelManagerInternalServerAddr:
fileManagerInternalServer:

objectStore:
  s3:
    endpointUrl:
    bucket:

awsSecret:
  name:
  accessKeyIdKey:
  secretAccessKeyKey:

database:
  host:
  port: 5432
  database: job_manager
  username:
  passwordEnvName: DB_PASSWORD

databaseSecret:
  name:
  key:

kubernetesManager:
  enableLeaderElection: false
  metricsBindAddress: :8080
  healthBindAddress: :8081
  pprofBindAddress:

debug:
  kubeconfigPath:
  useFakeJob: false

replicaCount: 1

serviceAccount:
  create: true
  serviceAccountName: job-manager-dispatcher

image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/job-manager-dispatcher
  pullPolicy: IfNotPresent

version:
