apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-manager-dispatcher.fullname" . }}
  labels:
    {{- include "job-manager-dispatcher.labels" . | nindent 4 }}
data:
  config.yaml: |
    jobPollingInterval: {{ .Values.jobPollingInterval }}
    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.database.username }}
      passwordEnvName: {{ .Values.database.passwordEnvName }}
    debug:
      autoMigrate: {{ .Values.debug.autoMigrate }}
