apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-manager-dispatcher.fullname" . }}
  labels:
    {{- include "job-manager-dispatcher.labels" . | nindent 4 }}
data:
  config.yaml: |
    jobPollingInterval: {{ .Values.jobPollingInterval }}
    jobNamespace: {{ .Values.jobNamespace }}
    modelManagerServerAddr: {{ .Values.modelManagerServerAddr }}
    modelStore:
      enable: {{ .Values.modelStore.enable }}
      mountPath: {{ .Values.modelStore.mountPath }}
      pvClaimName: {{ .Values.modelStore.pvClaimName }}
    database:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.database.username }}
      passwordEnvName: {{ .Values.database.passwordEnvName }}
    kubernetesManager:
      enableLeaderElection: {{ .Values.kubernetesManager.enableLeaderElection }}
      leaderElectionID: {{ include "job-manager-dispatcher.fullname" . }}
      metricsBindAddress: {{ .Values.kubernetesManager.metricsBindAddress }}
      healthBindAddress: {{ .Values.kubernetesManager.healthBindAddress }}
      pprofBindAddress: {{ .Values.kubernetesManager.pprofBindAddress }}
    debug:
      autoMigrate: {{ .Values.debug.autoMigrate }}
      kubeconfigPath: {{ .Values.debug.kubeconfigPath }}
      useFakeJob: {{ .Values.debug.useFakeJob }}
      huggingFaceAccessToken: {{ .Values.debug.huggingFaceAccessToken }}
