apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-manager-dispatcher.fullname" . }}
  labels:
    {{- include "job-manager-dispatcher.labels" . | nindent 4 }}
data:
  config.yaml: |
    pollingInterval: {{ .Values.pollingInterval }}
    llmOperatorBaseUrl: {{ .Values.global.llmOperatorBaseUrl }}
    job:
      image: {{ .Values.job.image }}
      version: {{ .Values.job.version }}
      imagePullPolicy: {{ .Values.job.imagePullPolicy }}
      numGpus: {{ .Values.job.numGpus }}
    modelManagerInternalServerAddr: {{ .Values.modelManagerInternalServerAddr }}
    fileManagerInternalServerAddr: {{ .Values.fileManagerInternalServerAddr }}
    objectStore:
      s3:
        endpointUrl: {{ .Values.global.objectStore.s3.endpointUrl }}
        region: {{ .Values.global.objectStore.s3.region }}
        bucket: {{ .Values.global.objectStore.s3.bucket }}
    database:
      host: {{ .Values.global.database.host }}
      port: {{ .Values.global.database.port }}
      database: {{ .Values.database.database }}
      username: {{ .Values.global.database.username }}
      passwordEnvName: DB_PASSWORD
    kubernetesManager:
      enableLeaderElection: {{ .Values.kubernetesManager.enableLeaderElection }}
      leaderElectionID: {{ include "job-manager-dispatcher.fullname" . }}
      metricsBindAddress: {{ .Values.kubernetesManager.metricsBindAddress }}
      healthBindAddress: {{ .Values.kubernetesManager.healthBindAddress }}
      pprofBindAddress: {{ .Values.kubernetesManager.pprofBindAddress }}
    kueueIntegration:
      enable: {{ .Values.kueueIntegration.enable }}
      defaultQueueName: {{ .Values.kueueIntegration.defaultQueueName }}
    debug:
      kubeconfigPath: {{ .Values.debug.kubeconfigPath }}
