apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "job-manager-dispatcher.fullname" . }}
  labels:
    {{- include "job-manager-dispatcher.labels" . | nindent 4 }}
data:
  config.yaml: |
    pollingInterval: {{ .Values.pollingInterval }}
    job:
      image: {{ .Values.job.image }}
      version: {{ .Values.job.version }}
      imagePullPolicy: {{ .Values.job.imagePullPolicy }}
      numGpus: {{ .Values.job.numGpus }}
      wandbApiKeySecret:
        name: {{ .Values.job.wandbApiKeySecret.name }}
        key: {{ .Values.job.wandbApiKeySecret.key }}
    notebook:
      llmOperatorBaseUrl: {{ .Values.global.llmOperatorBaseUrl }}
      ingressClassName: {{ .Values.notebook.ingressClassName }}
    clusterManagerServerWorkerServiceAddr: {{ .Values.clusterManagerServerWorkerServiceAddr }}
    jobManagerServerWorkerServiceAddr: {{ .Values.jobManagerServerWorkerServiceAddr }}
    fileManagerServerWorkerServiceAddr: {{ .Values.fileManagerServerWorkerServiceAddr }}
    modelManagerServerWorkerServiceAddr: {{ .Values.modelManagerServerWorkerServiceAddr }}
    worker:
      tls:
        enable: {{ .Values.global.worker.tls.enable }}
    objectStore:
      s3:
        endpointUrl: {{ .Values.global.objectStore.s3.endpointUrl }}
        region: {{ .Values.global.objectStore.s3.region }}
        bucket: {{ .Values.global.objectStore.s3.bucket }}
    kubernetesManager:
      enableLeaderElection: {{ .Values.kubernetesManager.enableLeaderElection }}
      leaderElectionID: {{ include "job-manager-dispatcher.fullname" . }}
      metricsBindAddress: {{ .Values.kubernetesManager.metricsBindAddress }}
      healthBindAddress: {{ .Values.kubernetesManager.healthBindAddress }}
      pprofBindAddress: {{ .Values.kubernetesManager.pprofBindAddress }}
    kueueIntegration:
      enable: {{ .Values.kueueIntegration.enable }}
      defaultQueueName: {{ .Values.kueueIntegration.defaultQueueName }}
    debug:
      kubeconfigPath: {{ .Values.debug.kubeconfigPath }}
