apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "job-manager-dispatcher.fullname" . }}
  namespace: {{ .Values.jobNamespace | default .Release.Namespace | quote }}
  labels:
    {{- include "job-manager-dispatcher.labels" . | nindent 4 }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
