apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "job-manager-dispatcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "job-manager-dispatcher.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
