grpcPort: 8081
httpPort: 8080

filelManagerServerAddr:
modelManagerInternalServerAddr:

database:
  host:
  port: 5432
  database: job_manager
  username:
  passwordEnvName: DB_PASSWORD

databaseSecret:
  name:
  key:

jobNamespace: default

debug:
  kubeconfigPath:

replicaCount: 1

serviceAccount:
  create: true
  serviceAccountName: job-manager-server

image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/job-manager-server
  pullPolicy: IfNotPresent

ingress:
  ingressClassName:

version:
