grpcPort: 8081
httpPort: 8080

filelManagerServerAddr:

database:
  host:
  port: 5432
  database: job_manager
  username:
  passwordEnvName: DB_PASSWORD

databaseSecret:
  name:
  key:

jobNamespace: default

debug:
  kubeconfigPath:

replicaCount: 1
image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/job-manager
  pullPolicy: IfNotPresent

ingress:
  ingressClassName:

version:
