grpcPort: 8081
httpPort: 8080
replicaCount: 1
image:
  repository: job-manager-server
  # TODO(kenji): Change this to IfNotPresent. Currently we set the pullPolicy
  # to Never as it is required to use a loaded image in a Kind cluster.
  pullPolicy: Never

version: latest
