global:
  database:
    host:
    port:
    username:

  databaseSecret:
    name:
    key:

  ingress:
    ingressClassName:

  auth:
    enable: true
    rbacInternalServerAddr:

httpPort: 8080
grpcPort: 8081

# The following default values work if model-manager-server runs in the same namespace.
fileManagerServerAddr: file-manager-server-grpc:8081
modelManagerServerAddr: model-manager-server-grpc:8081

database:
  database: job_manager

debug:
  kubeconfigPath:

notebook:
  # TODO(aya): build own image and think the way to switch the driver version
  imageTypes:
    jupyter-lab-base: cschranz/gpu-jupyter:v1.7_cuda-12.3_ubuntu-22.04_python-only
    jupyter-lab-full: cschranz/gpu-jupyter:v1.7_cuda-12.3_ubuntu-22.04

replicaCount: 1

serviceAccount:
  create: true

image:
  repository: public.ecr.aws/v8n3t7y5/llm-operator/job-manager-server
  pullPolicy: IfNotPresent

version:
