grpcPort: 8081
httpPort: 8080

database:
  host:
  port: 5432
  database: job_manager
  username:
  passwordEnvName: DB_PASSWORD

databaseSecret:
  name:
  key:

replicaCount: 1
image:
  repository: llm-operator/job-manager-server
  # TODO(kenji): Change this to IfNotPresent. Currently we set the pullPolicy
  # to Never as it is required to use a loaded image in a Kind cluster.
  pullPolicy: Never

version: latest
