global:
  database:
    host:
    port:
    username:

  databaseSecret:
    name:
    key:

  ingress:
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

  auth:
    enable: true
    rbacInternalServerAddr:

  workerServiceGrpcService:
    annotations:

  workerServiceIngress:
    create: false
    ingressClassName:
    annotations:
    tls:
      hosts:
      secretName:

httpPort: 8080
grpcPort: 8081
workerServiceGrpcPort: 8082

# The following default values work if model-manager-server runs in the same namespace.
fileManagerServerAddr: file-manager-server-grpc:8081
modelManagerServerAddr: model-manager-server-grpc:8081
sessionManagerServerEndpoint: http://session-manager-server-http:8080/v1

database:
  database: job_manager

notebook:
  # TODO(aya): build own image and think the way to switch the driver version
  imageTypes:
    jupyter-lab-base: mirror.gcr.io/cschranz/gpu-jupyter:v1.7_cuda-12.3_ubuntu-22.04_python-only
    jupyter-lab-full: mirror.gcr.io/cschranz/gpu-jupyter:v1.7_cuda-12.3_ubuntu-22.04

batchJob:
  images:
    pytorch-2.1: pytorch/pytorch:2.1.1-cuda12.1-cudnn8-runtime

replicaCount: 1

image:
  repository: public.ecr.aws/cloudnatix/llm-operator/job-manager-server
  pullPolicy: IfNotPresent

podAnnotations:
nodeSelector:
affinity:
tolerations:

version:

resources:
  requests:
    cpu: "250m"
    memory: "500Mi"
  limits:
    cpu: "250m"

livenessProbe:
  httpGet:
    path: /healthz
    port: http
    scheme: HTTP
  initialDelaySeconds: 3
  failureThreshold: 5
  timeoutSeconds: 3

podSecurityContext:
  fsGroup: 2000
securityContext:
  readOnlyRootFilesystem: true  
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
