name: CI-pre-merge
on:
  pull_request:
    branches:
    - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22
    - name: Run tests
      run: make test
    - name: Run lint checks
      run: make lint
