name: CI-post-merge
on:
  push:
    branches:
    - main

permissions:
  # This is necessary for AWS credentials. See:
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
  id-token: write
  contents: write

jobs:

  re-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22
    - name: Re-test
      run: make test

  update-tag:
    runs-on: ubuntu-latest
    needs:
    - re-test
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor

  docker-build:
    runs-on: ubuntu-latest
    needs:
    - update-tag
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker BUIldx
      uses: docker/setup-buildx-action@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::803339316953:role/github-actions-ecr-push-llm-operators
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registries: '803339316953'
        mask-password: "true"
    - name: Build, tag, and push dispatcher to Amazon ECR
      uses: docker/build-push-action@v5
      with:
        file: ./build/dispatcher/Dockerfile
        push: true
        tags: public.ecr.aws/v8n3t7y5/llm-operator/job-manager:dispatcher-${{ needs.update-tag.outputs.new_tag }}
    - name: Build, tag, and push server to Amazon ECR
      uses: docker/build-push-action@v5
      with:
        file: ./build/server/Dockerfile
        push: true
        tags: public.ecr.aws/v8n3t7y5/llm-operator/job-manager:server-${{ needs.update-tag.outputs.new_tag }}
    - name: Build, tag, and push fine-tuning to Amazon ECR
      uses: docker/build-push-action@v5
      with:
        context: ./build/experiments/fine-tuning
        push: true
        tags: public.ecr.aws/v8n3t7y5/llm-operator/job-manager:fine-tuning-${{ needs.update-tag.outputs.new_tag }}
