name: manual-build-and-push-fine-tuning
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag'
        required: true
        type: string
      image:
        description: 'Image name'
        required: true
        type: string
        default: fine-tuning

permissions:
  # This is necessary for AWS credentials. See:
  # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
  id-token: write
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::803339316953:role/github-actions-ecr-push-llmariners
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public
    - name: Build, tag, and push ${{ inputs.image }} to Amazon ECR
      uses: docker/build-push-action@v5
      with:
        context: ./build/${{ inputs.image }}
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          public.ecr.aws/v8n3t7y5/llm-operator/${{ inputs.image }}:${{ inputs.tag }}
          public.ecr.aws/v8n3t7y5/llm-operator/${{ inputs.image }}:latest
